[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"

[env]
  NODE_VERSION = "18" # Sostituisci con la versione di Node.js che utilizzi
